### PR TITLE
Changed rolesAllowed to routeOptions

### PR DESCRIPTION
**Pull request by taml**
I've made the recommended changes. I expect I've missed something / don't have something quite right, if so I'd really like to keep working on it until I get it right :)

### CODE REVIEW

**Review by XavierGeerinck — CHANGES_REQUESTED** [review]
In the `getAccessScope` the problem with the routeOptions is also there. You pass the routeOptions.allowedRoles in the `generateXXX` methods so that header should be: `getAccessScope (userScope, allowedRoles)` (I changed it to allowedRoles so it's used consistently in the file)

**Comment by thebillkidy** [comment]
Ok, I left feedback that should be changed. P.S. I will fix the conflicting files later since I made some changes about an hour ago that will probably break some things that you did :), but don't bother about that

**Comment by taml** [comment]
I figured I wouldn't get it right first time haha! So to be clear I need to update getAccessScope?

**Comment by thebillkidy** [comment]
Yes indeed! :)

**Comment by taml** [comment]
Awesome, so getAccessScope should look like this now?
`  getAccessScope (userScope, allowedRoles) {
        // if no user scope and rolesAllowed has been passed, then we return ALL_ACCESS
        if (!userScope && !allowedRoles) {
            return accessScopesEnum.ALL_ACCESS;
        }
etc`

**Comment by thebillkidy** [comment]
Correct!

**Comment by taml** [comment]
I've made changes, but I'm guessing it's still not quite right? Hopefully I'm pretty close to getting it right now though haha!

**Review by XavierGeerinck — APPROVED** [review]

**Comment by thebillkidy** [comment]
Ok, I created a PR on your fork so that I am able to merge this one (it should add the new commits to this PR then :) )

**Comment by thebillkidy** [comment]
Ok, closes #19

**Comment by taml** [comment]
I've just found it and merged it, and it looks like it's checking this changes on this PR now :)

**Comment by thebillkidy** [comment]
Indeed, it's now building on travis but should be successful since I checked it locally. I merged it into the main branch already :) thanks for helping!

**Comment by taml** [comment]
Thank you for providing the opportunity for me to help :) !

**Comment by thebillkidy** [comment]
👍

**Pull request merged**
